{{- if .Values.rbac.create }}
{{- range $namespace := (split "," (include "solr-operator.watchNamespaces" $)) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ include "solr-operator.roleType" $ }}Binding
metadata:
  name: {{ include "solr-operator.fullname" $ }}-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ include "solr-operator.roleType" $ }}
  name: {{ include "solr-operator.fullname" $ }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "solr-operator.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
{{- end }}
{{- end }}